// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KBS_Web.Models;

[Table("tbl_Buchungen", Schema = "dbo")]
public partial class TblBuchungen
{
    [Key]
    [Column("bu_BuchungsID")]
    public int BuBuchungsId { get; set; }

    [Column("kd_KundenID")]
    public int KdKundenId { get; set; }

    [Column("ed_EvDatenID")]
    public int EdEvDatenId { get; set; }

    [Column("bu_GebuchtePlaetze")]
    public int BuGebuchtePlaetze { get; set; }

    [Column("bu_Bezahlt")]
    public bool BuBezahlt { get; set; }

    [Column("bu_Storniert")]
    public bool BuStorniert { get; set; }

    [Column("bu_RechnungErstellt")]
    public bool BuRechnungErstellt { get; set; }

    [ForeignKey("EdEvDatenId")]
    [InverseProperty("TblBuchungens")]
    public virtual TblEventDaten EdEvDaten { get; set; }

    [ForeignKey("KdKundenId")]
    [InverseProperty("TblBuchungens")]
    public virtual TblKunden KdKunden { get; set; }
}