// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KBS_Web.Models;

[Table("tbl_EventDaten", Schema = "dbo")]
public partial class TblEventDaten
{
    [Key]
    [Column("ed_EvDatenID")]
    public int EdEvDatenId { get; set; }

    [Column("et_EventID")]
    public int EtEventId { get; set; }

    [Column("ed_Preis", TypeName = "smallmoney")]
    public decimal EdPreis { get; set; }

    [Column("ed_Beginn", TypeName = "datetime")]
    public DateTime EdBeginn { get; set; }

    [Column("ed_Ende", TypeName = "datetime")]
    public DateTime EdEnde { get; set; }

    [Required]
    [Column("ed_StartOrt")]
    [StringLength(50)]
    public string EdStartOrt { get; set; }

    [Column("ed_Zielort")]
    [StringLength(50)]
    public string EdZielort { get; set; }

    [Column("ed_MaxTeilnehmer")]
    public int EdMaxTeilnehmer { get; set; }

    [Column("ed_AktTeilnehmer")]
    public int EdAktTeilnehmer { get; set; }

    [Column("ed_Freigegeben")]
    public bool EdFreigegeben { get; set; }

    [Column("ed_Rabatt", TypeName = "decimal(18, 0)")]
    public decimal EdRabatt { get; set; }

    [Column("ed_VeranstalterBenachrichtigt")]
    public bool EdVeranstalterBenachrichtigt { get; set; }

    [ForeignKey("EtEventId")]
    [InverseProperty("TblEventDatens")]
    public virtual TblEvent EtEvent { get; set; }

    [InverseProperty("EdEvDaten")]
    public virtual ICollection<TblBuchungen> TblBuchungens { get; set; } = new List<TblBuchungen>();
}