// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KBS_Web.Models;

[Table("tbl_EvKategorie", Schema = "dbo")]
public partial class TblEvKategorie
{
    [Key]
    [Column("ek_EvKategorieID")]
    public int EkEvKategorieId { get; set; }

    [Required]
    [Column("ek_KatBezeichnung")]
    [StringLength(15)]
    public string EkKatBezeichnung { get; set; }

    [InverseProperty("EkEvKategorie")]
    public virtual ICollection<TblEvent> TblEvents { get; set; } = new List<TblEvent>();
}