// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KBS_Web.Models;

[Table("tbl_Events", Schema = "dbo")]
public partial class TblEvent
{
    [Key]
    [Column("et_EventID")]
    public int EtEventId { get; set; }

    [Column("ev_EvVeranstalterID")]
    public int EvEvVeranstalterId { get; set; }

    [Column("ek_EvKategorieID")]
    public int EkEvKategorieId { get; set; }

    [Required]
    [Column("et_Bezeichnung")]
    [StringLength(50)]
    public string EtBezeichnung { get; set; }

    [Column("et_Beschreibung", TypeName = "text")]
    public string EtBeschreibung { get; set; }

    [ForeignKey("EkEvKategorieId")]
    [InverseProperty("TblEvents")]
    public virtual TblEvKategorie EkEvKategorie { get; set; }

    [ForeignKey("EvEvVeranstalterId")]
    [InverseProperty("TblEvents")]
    public virtual TblEvVeranstalter EvEvVeranstalter { get; set; }

    [InverseProperty("EtEvent")]
    public virtual ICollection<TblEventDaten> TblEventDatens { get; set; } = new List<TblEventDaten>();
}